[workspace]
members = [
  "crates/common",
  "crates/dawless",
  "crates/dawless-akai",
  "crates/dawless-iconnectivity",
  "crates/dawless-korg",
  "crates/brailledump",
  "crates/hfedisk",
  "crates/laterna",
]
