[workspace]
members = [
  # UI framework
  "libs/thatsit",
  "libs/thatsit-fs",

  # Data formats
  "libs/opt-mod",
  "libs/brailledump",
  "libs/hfedisk",
  "libs/laterna",

  # App modules
  "app",
  "devices/akai",
  "devices/iconnectivity",
  "devices/korg",
]
